services:
  mysql:
    image: mysql:8.0
    container_name: devshop-mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: devshop

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-proot123",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: devshop-backend
    restart: always

    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: devshop-frontend
    restart: always

    ports:
      - "5173:5173"

    depends_on:
      - backend

volumes:
  mysql-data: