apiVersion: apps/v1
kind: Deployment
metadata:
  name: devshop-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devshop-backend
  template:
    metadata:
      labels:
        app: devshop-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/vishwaspg06/devshop-backend:latest
          ports:
            - containerPort: 5000

          env:
            - name: DB_HOST
              value: mysql

            - name: DB_PORT
              value: "3306"

            - name: DB_USER
              value: root

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password

            - name: DB_NAME
              value: devshop

            - name: PORT
              value: "5000"