apiVersion: apps/v1
kind: Deployment
metadata:
  name: devshop-frontend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: devshop-frontend

  template:
    metadata:
      labels:
        app: devshop-frontend

    spec:
      containers:
        - name: frontend
          image: ghcr.io/vishwaspg06/devshop-frontend:latest

          ports:
            - containerPort: 5173